name: Staged workflow
env:
  stage: 3
on:
  workflow_dispatch:
  schedule:
    - cron: 50 15 * * *
jobs:
  set_env:
    name: Set Environment variable
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.init.outputs.stage }}
    steps:
      - name: Environment variables to output
        id: init
        run: |
          echo "stage=${{ env.stage }}" >> $GITHUB_OUTPUT
  stage1:
    needs: set_env
    if: needs.set_env.outputs.stage == 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.5.0
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Stage 1
        run: echo "Hello from Stage 1"
      - name: Advance to Stage 2
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq &&\
          chmod +x ./yq
          export RUN_AT_CRON=$(date -d "now + 5 hours" "+%M %H * * *")
          ./yq -i '.run-name = "Staged workflow (Stage 2)" | .env.stage = 2 | .on.schedule[0].cron = strenv(RUN_AT_CRON)' .github/workflows/Staged.yml
      - name: Add test.txt file
        run: git add -A
      - name: Commit changes
        run: git commit --message "Advance to Stage 2"
      - name: Push branch
        run: git push origin main
  stage2:
    needs: set_env
    if: needs.set_env.outputs.stage == 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.5.0
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Stage 2
        run: echo "Hello from Stage 2"
      - name: Advance to Stage 3
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq &&\
          chmod +x ./yq
          export RUN_AT_CRON=$(date -d "now + 5 hours" "+%M %H * * *")
          ./yq -i '.run-name = "Staged workflow (Stage 3)" | .env.stage = 3 | .on.schedule[0].cron = strenv(RUN_AT_CRON)' .github/workflows/Staged.yml
      - name: Add test.txt file
        run: git add -A
      - name: Commit changes
        run: git commit --message "Advance to Stage 3"
      - name: Push branch
        run: git push origin main
  stage3:
    needs: set_env
    if: needs.set_env.outputs.stage == 3
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.5.0
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Stage 3
        run: echo "Hello from Stage 3"
      - name: Advance to Stage 4
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq &&\
          chmod +x ./yq
          export RUN_AT_CRON=$(date -d "now + 5 hours" "+%M %H * * *")
          ./yq -i '.run-name = "Staged workflow (Stage 4)" | .env.stage = 4 | .on.schedule[0].cron = strenv(RUN_AT_CRON)' .github/workflows/Staged.yml
      - name: Add test.txt file
        run: git add -A
      - name: Commit changes
        run: git commit --message "Advance to Stage 4"
      - name: Push branch
        run: git push origin main
  stage4:
    needs: set_env
    if: needs.set_env.outputs.stage == 4
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.5.0
        with:
          ref: main
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Stage 4
        run: echo "Hello from Stage 4"
      - name: Advance to Stage 1
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq &&\
          chmod +x ./yq
          ./yq -i '.run-name = "Staged workflow (Stage 1)" | .env.stage = 1 | del(.on.schedule)' .github/workflows/Staged.yml
      - name: Add test.txt file
        run: git add -A
      - name: Commit changes
        run: git commit --message "Advance to Stage 1"
      - name: Push branch
        run: git push origin main
run-name: Staged workflow (Stage 3)
