# This is a basic workflow that is manually triggered

name: Staged workflow

env:
  stage: 1

on:
  workflow_dispatch:

jobs:
  set_env:
    name: Set Environment variable 
    runs-on: ubuntu-latest         
    outputs:
      stage: ${{ steps.init.outputs.stage }}   
    steps:        
      - name: Environment variables to output 
        id: init
        run: |
          echo "stage=${{ env.stage }}" >> $GITHUB_OUTPUT
  
  stage1:
    needs: set_env
    if: needs.set_env.outputs.stage == 1
    runs-on: ubuntu-latest
    steps:
    - name: Stage 1
      run: echo "Hello from Stage 1"

  stage2:
    needs: set_env
    if: needs.set_env.outputs.stage == 2
    runs-on: ubuntu-latest
    steps:
    - name: Stage 2
      run: echo "Hello from Stage 2"

  stage3:
    needs: set_env
    if: needs.set_env.outputs.stage == 3
    runs-on: ubuntu-latest
    steps:
    - name: Stage 3
      run: echo "Hello from Stage 3"

  stage4:
    needs: set_env
    if: needs.set_env.outputs.stage == 4
    runs-on: ubuntu-latest
    steps:
    - name: Stage 4
      run: echo "Hello from Stage 4"
