# Simple workflow for deploying static content to GitHub Pages
name: Start long task

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:

    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v2.5.0
          with:
            ref: main
            token: ${{ secrets.WORKFLOW_TOKEN }}

        - name: Initialize mandatory git config
          run: |
           git config user.name "GitHub Actions"
           git config user.email noreply@github.com
           
        - name: Write to file
          run: |
            cp ./.github/workflows/templates/runAt.yml ./.github/workflows/123.yml
            sed -i 's|{{workflow}}|./.github/workflows/e2e1.yml|g' ./.github/workflows/123.yml
            cron=$(date -d "now + 5 hours" "+%M %H * * *")
            sed -i 's/{{cron}}/$cron/g' ./.github/workflows/123.yml
          
            

        - name: Add test.txt file
          run: git add -A

        - name: Commit changes
          run: git commit --message "Schedule task"

        - name: Push branch
          run: git push origin main

