# Simple workflow for deploying static content to GitHub Pages
name: Test workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
        - name: Set and Retrieve Github ENV variables
          shell: bash
          run: echo "TEST=world" >> $GITHUB_ENV

