
# Simple workflow for deploying static content to GitHub Pages
name: Test workflow 2

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jorgebg/stateful-action@v0.1
    - name: Test Run
      run: echo $(date)\n >> .state/data.txt
