# Simple workflow for deploying static content to GitHub Pages
name: Test workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v2.5.0
          with:
            ref: test
        - name: Write to file
          run: echo "some data for the file" >> test.txt

        - name: Add test.txt file
          run: git add test.txt

        - name: Commit changes
          run: git commit --message "add text to test.txt"

        - name: Push branch
          run: git push origin test
