
# Simple workflow for deploying static content to GitHub Pages
name: Test workflow 2

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  get_state:
    uses: ./.github/workflows/getState.yml
    with:
      key: new_key

  print_state:
    runs-on: ubuntu-latest
    needs: get_state
    steps:
    - name: Test Run
      run: echo ${{ needs.get_state.outputs.new_key }}
