# Simple workflow for deploying static content to GitHub Pages
name: Test workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:        
        - name: Write to file
          run: echo "some data for the file" >> test.txt
        - name: Upload math result for job 1
          uses: actions/upload-artifact@v4
          with:
            name: test.txt
            path: test.txt
        
