# Simple workflow for deploying static content to GitHub Pages
name: Write state

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage name?'
        required: true
        type: text
  workflow_call:
    inputs: 
      stage:
        required: true
        type: string

jobs:
  update_state:
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v2.5.0
          with:
            ref: state

        - name: Initialize mandatory git config
          run: |
           git config user.name "GitHub Actions"
           git config user.email noreply@github.com

        - name: Remove file
          run: rm -f state.txt
          
        - name: Write stage to file
          run: echo "stage=${{ inputs.environment }}" >> state.txt
          
        - name: Write timestamp to file
          run: echo "timestamp="date +%s >> state.txt

        - name: Add test.txt file
          run: git add state.txt

        - name: Commit changes
          run: git commit --message "add text to test.txt"

        - name: Push branch
          run: git push origin state
